### ISSUE TITLE
HPA v2beta2 is deprecated in v1.23+, unavailable in v1.26+

### ISSUE THREAD

**Issue by svrdoljak** [meredrica/helm#8]
Our builds fail because the v2beta2 is deprecated with the following error message:

"autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2 HorizontalPodAutoscaler"

Can we have a new release with the newer HPA API version?

**Comment by svrdoljak** [comment]
I need to correct myself. The builds are not failing, this is just a warning.

**Comment by meredrica** [comment]
forgot to close this. was fixed with `0.0.7`
